# name: Build Marlin Cloud

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout user configs
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PlatformIO
      run: |
        pip install -U platformio
        
    - name: Inject Custom Configurations
      run: |
        # Папка теперь называется Marlin-2.1.2
        cp Configuration.h Marlin-2.1.2/Marlin/Configuration.h
        cp Configuration_adv.h Marlin-2.1.2/Marlin/Configuration_adv.h
    - name: Compile Firmware
      run: |
        # Переходим в правильную папку
        cd Marlin-2.1.2
        pio run -e BIGTREE_SKR_PRO

    - name: Upload Ready Firmware
      uses: actions/upload-artifact@v4
      with:
        name: SKR_Pro_Firmware_2.1.2
        # Путь тоже нужно обновить
        path: Marlin-2.1.2/.pio/build/BIGTREE_SKR_PRO/*.bin
